=== SysImp/ServiceExchangeRates/src/main/resources/xml/currnecyTemplate.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="currencies">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="currency" maxOccurs="10">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:integer"/>
                            <xs:element name="name" type="xs:string" >
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="USD" />
                                        <xs:enumeration value="RUB" />
                                        <xs:enumeration value="EUR" />
                                        <xs:enumeration value="SOS" />
                                        <xs:enumeration value="AZN" />
                                        <xs:enumeration value="HKD" />
                                        <xs:enumeration value="ARS" />
                                        <xs:enumeration value="MYR" />
                                        <xs:enumeration value="BTC" />
                                        <xs:enumeration value="PLN" />
                                        <xs:enumeration value="AUD" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="description" type="xs:string" nillable="true"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SysImp/ServiceExchangeRates/src/main/resources/xml/currnecyTemplate.xml
<?xml version="1.0" encoding="utf-8"?>
<currencies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="currnecyTemplate.xsd">
    <currency>
        <id>1</id>
        <name>USD</name>
        <description>Доллар США</description>
    </currency>
    <currency>
        <id>2</id>
        <name>RUB</name>
        <description>Российский рубль</description>
    </currency>
    <currency>
        <id>3</id>
        <name>EUR</name>
        <description>Европейская валюта</description>
    </currency>
    <currency>
        <id>4</id>
        <name>SOS</name>
        <description>Сомалийский шиллинг</description>
    </currency>
    <currency>
        <id>5</id>
        <name>AZN</name>
        <description>Азербайджанский манат</description>
    </currency>
    <currency>
        <id>6</id>
        <name>HKD</name>
        <description>Гонконгский доллар</description>
    </currency>
    <currency>
        <id>7</id>
        <name>BTC</name>
        <description>Биткойн</description>
    </currency>
    <currency>
        <id>8</id>
        <name>MYR</name>
        <description>Малайзийский ринггит</description>
    </currency>
    <currency>
        <id>9</id>
        <name>AUD</name>
        <description>Австралийский доллар</description>
    </currency>
</currencies>
